CREATE TABLE IF NOT EXISTS merchants (
    id              bigint                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255)            NOT NULL,
    email           varchar(255)            DEFAULT NULL,
    webhook         varchar(255)            NOT NULL,
    tax_number      varchar(9)              NOT NULL,
    login           varchar(255)            NOT NULL,
    password        varchar(80)             NOT NULL,
    created_at      TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_merchants_tax_number UNIQUE (tax_number),
    CONSTRAINT uk_merchants_login UNIQUE (login)
);

CREATE TYPE notification_status AS ENUM ('CREATED', 'SENT', 'FAILED');
CREATE TYPE notification_type AS ENUM ('SMS', 'EMAIL', 'PUSH');

CREATE TABLE IF NOT EXISTS notifications (
    id              bigint                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status          notification_status     NOT NULL,
    created_at      TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    text            varchar(255)            NOT NULL,
    merchant_id     bigint                  NOT NULL,
    type            notification_type       NOT NULL,
    receiver_info   varchar(255)            NOT NULL,

    CONSTRAINT fk_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE
);
