CREATE TYPE unit_of_measure AS ENUM ('KILOGRAM', 'GRAM', 'LITER', 'MILLILITER', 'PIECE');

CREATE TABLE IF NOT EXISTS ingredients (
    id              bigint                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255)            NOT NULL,
    is_active       boolean                 NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_ingredients_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS foods (
    id              bigint                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255)            NOT NULL,
    price           numeric(10, 2)          NOT NULL,
    category_id     bigint                  NOT NULL,
    is_active       boolean                 NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_foods_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS food_receipt_items (
    food_id         bigint                  NOT NULL,
    ingredient_id   bigint                  NOT NULL,
    quantity        numeric(10, 3)          NOT NULL,
    measure         unit_of_measure         NOT NULL,

    CONSTRAINT fk_food_receipt FOREIGN KEY (food_id) REFERENCES foods (id) ON DELETE CASCADE,
    CONSTRAINT fk_ingredient_receipt FOREIGN KEY (ingredient_id) REFERENCES ingredients (id)
);

CREATE INDEX idx_food_receipt_items_food_id ON food_receipt_items(food_id);